### ISSUE TITLE
Request for help?

### ISSUE THREAD

**Issue by ayandagatsha** [MiguelAngelLopezGarcia/Hangman#1]
Hi Miguel! I've reached the files and serialization lessons of the odin project and I am currently struggling to implement a save feature to my rock paper scissors game similar to your save feature in this hangman open source project. I'm hoping you could help me? https://repl.it/@ayandagatsha/rps-v2#main.rb

**Comment by MiguelAngelLopezGarcia** [comment]
Hi! Sure thing! I'm more than wiling to help you! 

First thing (this is just a recommendation, I'm not English native) it's that you may want to change the word "game" for "round" maybe... It made me get a bit confused (in my mind I play a single game with a number of rounds in it).

Ok, lets get into the save thing! What I did in this project of the Hangman was to save a current class instance, so if you were to play a game with this save file, what it really does is to assign a variable (in my case the name was "play") this class instance. Instead, if you were to play a new game, this variable "play" will be a new class instance with the default values (what I mean with "default values" is the class instance variable, the "@secret_word" for example).

If I were you I'll wrap the actual game into the "ParentClass" class that you have, change the name of it for something more readable (like "Rock_Paper_Scissors_Game" or something that anyone can understand what it does) and include class instance variables (like "@rounds_won" and "@rounds_lost") in where I'll store this info and that will be the thing that will be saved. Also I don't understand the use of the class "ChildClass" (I'm no expert so everything that I can tell you could be wrong, I'm just telling you what I may do).

Oh! Also do not have the save file from the beginning! Your actual code is checking at the beginning of the game if this file exists, so if it's empty you don't want it! Do the same as with "mkdir" but with the file. 

This is my recommendation for you! I don't know if I'm right in everything but I'm really glad that you ask me for help, you made my day :) I hope to have been helpful somehow! And if you have some questions left or something it's not clear let me know!

Have a nice day and keep going! You are doing it great!

**Comment by ayandagatsha** [comment]
Hey, I'm glad I made your day, your project was the only one that gave me hope because I saw you were able to do it all in one file. which is what I wanted to do to make it easier for me to return and read the code again. 

Yes, I understand my current code has readability issues, it is because I am still wrapping my head around OOP.. it seems to be tricky for me. 

Could we exchange discord, emails or WhatsApp? Any way of communicating directly so that perhaps we can keep in better touch and help each other whenever we need it?

I will try what you suggested, but may I also ask if you could try make a rock paper scissors game with a save function too so that we can compare my attempts with your attempts and I can better see where I went wrong?

**Comment by MiguelAngelLopezGarcia** [comment]
Sure thing! Here is my Discord account: Monoyonky#4168

I'll close this issue as we will be communicating via Discord :)
